name: Buat Sesi RDP Sementara

on:
  workflow_dispatch:

jobs:
  rdp_session:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: 1. Instalasi Lingkungan Desktop dan Server RDP
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive \
            apt-get install -y xfce4 desktop-base xfce4-terminal xrdp

      - name: 2. Konfigurasi Server RDP
        run: |
          echo xfce4-session > ~/.xsession
          sudo adduser xrdp ssl-cert
          sudo systemctl restart xrdp

      - name: 3. Buat Akun Pengguna untuk RDP
        run: |
          sudo useradd -m -s /bin/bash rdp
          echo "rdp:${{ secrets.RDP_PASSWORD }}" | sudo chpasswd
          echo "Akun RDP dibuat dengan username: rdp"

      - name: 4. Jalankan Tunnel Playit.gg (URL DIPERBARUI)
        run: |
          # Mengunduh file agen playit dengan nama yang benar untuk arsitektur x86_64 Linux
          # Lalu menyimpannya sebagai 'playit' agar perintah selanjutnya tetap berfungsi.
          wget -O playit https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64
          chmod +x playit
          echo "Menjalankan Playit Tunnel... Cari alamat RDP Anda di log di bawah ini."
          echo "${{ secrets.PL }}" | ./playit -s &

      - name: 5. Jaga Sesi Tetap Aktif (HUBUNGKAN SEKARANG!)
        run: |
          echo "===================================================================="
          echo "Sesi RDP Siap! Silakan hubungkan menggunakan alamat dari log Playit."
          echo "Sesi ini akan tetap aktif selama sekitar 6 jam sebelum dimatikan."
          echo "===================================================================="
          sleep 21000
